dailyTriggers: 
  - 今日
  - 每日
  - 日常
  - daily
  - Daily
animeTriggers: 
  - 番剧
  - 动画
  - B 站番剧
  - B站番剧
newsTriggers: 
  - 新闻
  - 速报
  - 新闻速报
touchfishTriggers: 
  - 摸鱼日历
  - 摸鱼人日历
separators: 
  - ' '
  - '-'
waitMessages: 
  - 稍等哦 QwQ
animeDailyMessages: 
  - "早上好呀, 这是今天的 B 站番剧 \n( •̀ ω •́ )✧"
animeReplyMessages: 
  - "这是今天的 B 站番剧 \n( •̀ ω •́ )✧"
noAnimeMessages: 
  - '好像今天没有放送呢 >_<'
newsDailyMessages: 
  - "早上好呀, 这是今天的新闻速报 \nq(≧▽≦q)"
newsReplyMessages: 
  - "这是今天的新闻速报 \nq(≧▽≦q)"
touchfishDailyMessages: 
  - "摸鱼时间到～～这是今天的摸鱼日历 \n(≖‿≖)✧"
touchfishReplyMessages: 
  - "这是今天的摸鱼日历 \n(≖‿≖)✧"
noDisturbingGroupMessages: 
  - 为了防止打扰到网友，这个群不在日报白名单呢 QwQ
errorMessages: 
  - 出错啦, 等会再试试吧 ￣へ￣