# ! ! !警告! ! !
# 修改以下选项可能导致你的机器人被其他人控制
# 控制模式
# 0 主人可以控制
# 1 拥有权限(admin)者可控
# 修改后可自动加载变更
mode: 0
# 主人的QQ号
masterID: 
  - 599423132
# 没有权限时的提示词
tip: 我才不会听你的话呢!(σ｀д′)σ
# 没有内容时的提醒次
nullTip: 喂喂，什么都没有啊！(￣_,￣ )
# 没有此群的提醒词
noGroup: 没有加入这个群哦(～￣▽￣)～
# 无权撤回
notRecall: 没有权力撤回别人的发言
# 撤回超时(不知道为啥这玩意用不了)
outOffTimeRecall: 发言就像泼出去的水，收不回来啦
# 取消发送的关键字
cancelWord: 取消
# 取消发送成功
canceled: 好哒
# 获取下一条消息(send指令)时的提示语句
waitingNextMessage: "请发送需要发送的消息，如需取消请发送 '取消' (记得去掉单引号ヾ(•ω•`)o)"
# 获取下一条消息(send指令)时的等待时间
waitTime: 30000
# 通过回复撤回消息时，若没有找到回复消息
referenceNotFound: 没有找到你说的这条消息呢ㄟ( ▔, ▔ )ㄏ
# 撤回指令的前缀
recallCommand: 
  - '/撤回'